### ISSUE TITLE
implement i18n in the validator

### ISSUE THREAD

**Issue by frodrigo** [Jungle-Bus/transport_mapcss#11]
Some rules are already limited to France, but others not.
At this time, the use of this mapcss file in Osmose is limited to France due to language.

I aim to use this mapccs file content in place of some rules written directly in Python, but this rules should apply worldwide... and so written in english.

**Comment by nlehuby** [comment]
It would be great indeed to have these added into Osmose from a single source file.

But replacing all the French error messages by English ones is not an option. OSM validation is a complex topic, we should provide the messages in the language of the user (in JOSM and in Osmose).
Let's rename this issue to "implement i18n in the validator".

**Comment by frodrigo** [comment]
Standard JOSM MapCSS files are translated like the JOSM core. But the contrib MapCSS files are not.
In Osmose all the MapCSS are translated, using the JOSM translation if possible.

**Comment by stoecker** [comment]
What's the state of this. Does it work as expected now?

**Comment by frodrigo** [comment]
I implemented it as requested in:
https://github.com/frodrigo/transport_mapcss/tree/i18n
But I don't now about the effective status of it. I do not test it, as it's not possible for now. I have implemented it for Osmose-QA.

@nlehuby contacted the JOSM team for dev the missing part to support it on JOSM side.

**Comment by stoecker** [comment]
> @nlehuby contacted the JOSM team for dev the missing part to support it on JOSM side.

I know. That's why I ask. I implemented this 7 days ago.

**Comment by nlehuby** [comment]
We have a pull request here: https://github.com/Jungle-Bus/transport_mapcss/pull/12
We will wait for the i18n feature to be in the stable version of JOSM to merge, to avoid to break the rules for the current French users.

You did not update the doc though, do we have to put the url of zip in the wiki instead of the mapcss one ? Do we have to provide both ?

**Comment by stoecker** [comment]
>You did not update the doc though, do we have to put the url of zip in the wiki instead of the mapcss one ?

Yes

>Do we have to provide both ?

No.

Thought there is no automatic update from one to the other, as the links are name based. Which BTW also means you wont break existing users with older JOSM version due to the name change.

**Comment by nlehuby** [comment]
I just tried to use the zip in JOSM (v 13518) instead of the mapcss file, and it looks good: the custom rules are added to the validator, and they are in my language.

**Comment by nlehuby** [comment]
@stoecker it does not seem to work: the wiki now have the zip url, but JOSM keep on using the mapcss file (which is kaputt for existing users, as it is now in English instead of French)

**Comment by stoecker** [comment]
Citing myself:
> Thought there is no automatic update from one to the other, as the links are name based.

The new entry works, but the old entry will not be automatically updated to new link, as the name differs.

I'd make the old link unavailable, then users will know at least in 2 weeks, that they need to reactivate the rule. Only for maps there is a method to handle renames/removals/changes. Not for the other external types.

That's why JOSM wiki always delivers zip files even when only the CSS file is inside. So that the name does not change when files are added.

**Comment by stoecker** [comment]
BTW: Could you please change the included link http://junglebus.io/ to https://junglebus.io/? See https://josm.openstreetmap.de/ticket/16123.

**Comment by prhod** [comment]
I tried the last package in a french JOSM, and messages are not consistent with the error.
For exemple: 
I load the 7993124 relation -> no error.
If a delete the `network` tag, I have the error `Est-ce un arrêt ou une gare routière ?`.
Then if I delete the `network` tag, the new error is `Vérifier l'opérateur sur le tag operator`

**Comment by stoecker** [comment]
Download is broken, so I can't test, but if strings mismatch this is usually a sign the en.lang and fr.lang don't match. Like stated int the documentation they must always been handled as a set. It is not poosible e.g. to update only fr.lang file.

**Comment by nlehuby** [comment]
We remove the last zip as nothing worked as expected.
New PR here: https://github.com/Jungle-Bus/transport_mapcss/pull/15
current zip here: https://github.com/Jungle-Bus/transport_mapcss/blob/i18n_tofix/transport.validator.zip

**Comment by stoecker** [comment]
This can't work: en has 6 entries, french has 24. And the texts don't match even for the 6.
> langinfo.pl data/en.lang 
   1    56 Missing from/to tag on a public_transport route relation
   2    45 Missing legacy tag on a public transport stop
   3    50 Missing network tag on a public_transport relation
   4    51 Missing operator tag on a public_transport relation
   5    55 Missing public_transport tag on a public transport stop
   6    73 Missing public_transport:version tag on a public_transport route relation
multi:
Status: Missing 0/0 - 6,0,0,0,0
> langinfo.pl data/fr.lang 
   1    42 Vérifier si la note peut être supprimée                                                                                                                                                                                                                             
   2    36 Vérifier le réseau sur tag network                                                                                                                                                                                                                                  
   3    43 Vérifier l''opérateur sur le tag operator                                                                                                                                                                                                                           
   4    47 Est-ce un arrêt de bus ou une gare routière ?                                                                                                                                                                                                                       
   5    57 Est-ce un arrêt de bus ? ajouter le tag highway=bus_stop                                                                                                                                                                                                            
   6    62 L''origine/destination est manquante, ajouter les tags from/to                                                                                                                                                                                                      
   7    50 Le tag de transport public historique est manquant                                                                                                                                                                                                                  
   8    47 Le réseau est manquant, ajouter un tag network                                                                                                                                                                                                                      
   9    51 L''opérateur est manquant, ajouter un tag operator
  10    47 Il manque le tag public_transport sur un arrêt
  11    62 Le mode est manquant, transformer le tag route en route_master
  12    52 Le numéro de ligne est manquant, ajouter un tag ref
  13    63 Le mode est manquant, ajouter un tag route = bus/coach/tram/etc
  14    70 Le mode est manquant, ajouter un tag route_master = bus/coach/tram/etc
  15    98 Préciser s''il s''agit d''un arrêt (platform) ou d''un emplacement sur les rails (stop_position)
  16    97 Préciser s''il s''agit d''un arrêt (platform) ou d''un emplacement sur la route (stop_position)
  17    25 L''arrêt n''a pas de nom
  18    81 Le tag historique est manquant, ajouter le tag highway=bus_stop/railway=tram_stop
  19    91 La variante de ligne n''appartient à aucune ligne (l''ajouter à la relation route_master)
  20    82 Le réseau devrait être porté par les lignes de transport et non par les arrêts
  21    85 L''opérateur devrait être porté par les lignes de transport et non par les arrêts
  22    77 L''arrêt n''est desservi par aucune ligne (l''ajouter à une relation route)
  23    52 Les arrêts ne sont peut-être pas dans le bon ordre
  24    65 Une validation intransigeante des données de transport en commun
multi:
Status: Missing 0/0 - 24,0,0,0,0

You should check your build process!

Also as said mapcss actually does not really belong into data directory.

**Comment by nlehuby** [comment]
:+1:
