### ISSUE TITLE
There is no description :(

### ISSUE THREAD

**Issue by nlehuby** [Jungle-Bus/transport_mapcss#18]
The description field is set in the metadata, but the description does not show up, neither in JOSM, neither in the wiki: https://josm.openstreetmap.de/wiki/Rules

```
description: tr("Uncompromising validation of transit data");
```

Is the use of the `tr` function forbidden here ? 
Any ideas @Klumbumbus @stoecker ?

**Comment by stoecker** [comment]
No tr() in the meta. Meta uses the [lang=de] syntax. See e.G. https://josm.openstreetmap.de/wiki/Rules/GermanySpecific
You can try. JOSM probably translates these texts if you provide them in lang-files. In this case server code needs to be adapted to do as well.

**Comment by nlehuby** [comment]
We have added the `[lang=*]` in the mapcss file.
It is ok with JOSM (here in French)
![image](https://user-images.githubusercontent.com/919962/41175856-c02fb128-6b5e-11e8-84f7-83d2a96cf5d5.png)

But the wiki still don't have any description.

**Comment by stoecker** [comment]
> But the wiki still don't have any description.

What do you mean?

E.g. https://josm.openstreetmap.de/wiki/Nl%3ARules is correctly translated.

**Comment by nlehuby** [comment]
My bad, you are right. We forgot to manually add the `[lang=en]` description :disappointed:

**Comment by frodrigo** [comment]
We keep it to be cached by the translation process.
We will try to do it in an other way.
