### ISSUE TITLE
Missing legacy tag on a public transport stop

### ISSUE THREAD

**Issue by maro-21** [Jungle-Bus/transport_mapcss#43]
[copy from https://github.com/osm-fr/osmose-backend/issues/789]

Osmose suggests missing `railway=tram_stop` for:
```
public_transport = platform
tram = yes
```
on standalone points [they are not a vertex on `railway=tram`].
But this is a correct tram stop. There is even such preset in iD called "Tram Stop / Platform".
In public transport version 2 correct tagging is:
```
public_transport = stop_position
railway = tram_stop
tram = yes
````
as a vertex on `railway=tram`
plus
```
public_transport = platform
tram = yes
```
as a point.

So `railway=tram_stop` is already on a `railway` feature.

Correct me if I'm wrong.

https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram_stop
"This tag is one way to mark a tram stop. It is used on tram tracks (railway=tram) and also on light rail tracks (railway=light_rail)"

http://osmose.openstreetmap.fr/en/map/?#zoom=13&lat=51.115&lon=17.0514&item=2140&level=1%2C2%2C3&tags=&fixable=

So I think for standalone points tagged
`public_transport=platform` [and no other tags]
it shouldn't suggest 

> The legacy tag is missing, add the tag highway=bus_stop / railway=tram_stop

But rather something like "... add the tag highway=bus_stop / tram=yes"
Because `railway=tram_stop` should be used on `railway=tram` ways

and for 
`public_transport=platform` + `tram=yes` there shouldn't be an issue.

So would changing this 
`node[public_transport=platform][!highway][!railway][!bus]`
https://github.com/Jungle-Bus/transport_mapcss/blob/98bf41d8887f609c5196332176feeec8bc1a5da6/transport.validator.mapcss#L233
to
`node[public_transport=platform][!highway][!railway][!bus][!tram]`
solve the issue?

**Comment by nlehuby** [comment]
Thanks for this detailed report.

It seems good to me and your change proposal is ok :+1:  
Do you want to make a pull request here ? (if not I will do it)

**Comment by maro-21** [comment]
No, I'm not good at it, you can do it :)
BTW, not to open a new issue: could you also update translations? I've recently translated all strings for Polish.
