### ISSUE TITLE
bus=yes ou tram=yes manquant

### ISSUE THREAD

**Issue by Bibi56** [Jungle-Bus/transport_mapcss#46]
https://github.com/Jungle-Bus/transport_mapcss/blob/master/transport.validator.mapcss
Si aucune ligne de tram ne passe dans le coin on devrait proposer d'ajouter `bus=yes` et non dire qu'il faut ajouter un attribut (sans préciser par ailleurs d'ajouter `bus=yes` ou `tram=yes`).

**Comment by nlehuby** [comment]
De quel test s'agit-il ?
Et comment peut-on détecter qu'aucune ligne de tram ne passe dans le coin ?
