### ISSUE TITLE
Broken link on JOSM wiki for this rule

### ISSUE THREAD

**Issue by tsmock** [Jungle-Bus/transport_mapcss#54]
https://github.com/Jungle-Bus/transport_mapcss/raw/gh-pages/transport.validator.zip doesn't seem to exist anymore. You can update the link at https://josm.openstreetmap.de/wiki/RulesSource .

See https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.validator/ValidatorTagCheckerRulesPreferenceTestIT/Jungle_Bus___validation_ruleset___https___github_com_Jungle_Bus_transport_mapcss_raw_gh_pages_transport_validator_zip/ for the test which alerted us to the broken link.

**Comment by nlehuby** [comment]
Thank you for the notice, I just fixed it.

**Comment by tsmock** [comment]
Thank you.
